# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: "Potential National Dialogue Nominees"
email:
description: "Information you need to complete your nomination info"
baseurl: "/nationaldialogue_"
url: "https://iceboogey.github.io/nationaldialogue_"
#twitter_username: "gustavoquinalha"
#github_username:  "gustavoquinalha"
color_theme:  "#00cc00"
color_text:  "#fff"
language:  "en"

# Build settings
markdown: kramdown
permalink: /:title/
plugins: [jekyll-paginate]
paginate: 5

# Plugins
plugins_dir:
  - jekyll-admin
